### ISSUE TITLE
Why not tailwind css

### ISSUE THREAD

**Issue by stabldev** [TheoIsDumb/TheoOS#1]
Hey dude! nice project
It seems like you're using vanilla css for styling, why not tailwind?

Malayali? lol

**Comment by theophinetheodore** [comment]
@tokitou-san i have heard good things about tailwind, but i haven't gotten myself to actually use it. 😅
idk, but the long utility classes make me turn it down, but i'll try it soon.

and yes, മലയാളി ആണ് hehe

**Comment by stabldev** [comment]
> @tokitou-san i have heard good things about tailwind, but i haven't gotten myself to actually use it. sweat_smile
idk

Yea, I would suggest - use this project to learn it
feel free to close this
>but the long utility classes make me turn it down, but i'll try it soon.

You can use `@apply` method to solve this
> and yes, മലയാളി ആണ് hehe

sheri enna XD

**Comment by theophinetheodore** [comment]
@tokitou-san thank you, sir! i'll give tailwind a try!
